language: java
jdk: oraclejdk8
sudo: required

before_script:
  - psql -U postgres -c 'CREATE DATABASE "uatransport";'
  - psql -U postgres -c "ALTER USER postgres WITH PASSWORD '1';"
#  - psql -c "CREATE USER postgres WITH PASSWORD '1';" -U postgres

services:
  postgresql

install:
  mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  mvn clean install

#before_install:
#- jdk_switcher use oraclejdk8

branches:
  only:
    deploy

notifications:
  email:
    s.turchynskyi@gmail.com