language: java
jdk: oraclejdk8

before_script:
  - sudo psql -c 'create database uaTransport;' -U postgres
  - psql -c "SELECT * FROM pg_catalog.pg_tables;" -U postgres
  - psql -c "ALTER USER postgres WITH PASSWORD '1';" -U postgres
#  - psql -c "CREATE USER postgres WITH PASSWORD '1';" -U postgres

services:
  postgresql

addons:
  postgresql: "9.6"

install:
  mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  mvn clean install

#before_install:
#- jdk_switcher use oraclejdk8

branches:
  only:
    deploy

notifications:
  email:
    s.turchynskyi@gmail.com