language: java
jdk: oraclejdk8
sudo: required

services:
  postgresql

before_script:
  - psql -c "CREATE DATABASE uatransport;" -U postgres
  - psql -c "ALTER USER postgres WITH PASSWORD '1';" -U postgres
#  - psql -c "CREATE USER postgres WITH PASSWORD '1';" -U postgres

install:
  mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  mvn clean install

#before_install:
#- jdk_switcher use oraclejdk8

branches:
  only:
    deploy

notifications:
  email:
    s.turchynskyi@gmail.com