language: java
jdk: oraclejdk8

services:
  postgresql

before_script:
  - psql -c 'create database uatransport;' -U postgres

addons:
  postgresql: "9.6"

before_install:
  - jdk_switcher use oraclejdk8

install:
#  mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn package

before_deploy:
  - cd target
  - zip -r server *
  - mkdir -p upload
  - mv server.zip upload/server.zip
  - cd ..
#  - pwd
#  - cd target/jar
#  - zip -rm server *
#  - ls /home/travis/build/44stv/Lv-318.Java/target/jar/

#before_deploy:

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    skip_cleanup: true
    on: &2
      branch: deploy
    bucket: travisdeploybucket
    region: eu-central-1
    local-dir: upload
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: travisdeploybucket
    key: server.zip
    bundle_type: zip
    application: ServerCodedeployApplication
    deployment_group: ServerDeploymentGroup
    region: eu-central-1
    on: *2

cache:
  directories:
  - $HOME/.m2

branches:
  only:
    deploy

notifications:
  email:
    s.turchynskyi@gmail.com