INSERT INTO public.question (id, name, weight, criteria_id, type) VALUES (33, 'о котрій годині вийшли?', 18, 18, 'TIME');
INSERT INTO public.question (id, name, weight, criteria_id, type) VALUES (32, 'о котрій годині виїхали?', 18, 18, 'TIME');
INSERT INTO public.question (id, name, weight, criteria_id, type) VALUES (39, 'о котрій годині вийшли?', 20, 18, 'TIME');
INSERT INTO public.question (id, name, weight, criteria_id, type) VALUES (38, 'о котрій годині вийшли?', 19, 19, 'TIME');
INSERT INTO public.question (id, name, weight, criteria_id, type) VALUES (37, 'о котрій годині виїхали?', 20, 18, 'TIME');
INSERT INTO public.question (id, name, weight, criteria_id, type) VALUES (36, 'о котрій годині виїхали?', 19, 19, 'TIME');
INSERT INTO public.question (id, name, weight, criteria_id, type) VALUES (26, 'о котрій годині вийшли?', 16, 16, 'TIME');
INSERT INTO public.question (id, name, weight, criteria_id, type) VALUES (25, 'о котрій годині виїхали?', 16, 16, 'TIME');
INSERT INTO public.question (id, name, weight, criteria_id, type) VALUES (30, 'о котрій годині вийшли?', 17, 17, 'TIME');
INSERT INTO public.question (id, name, weight, criteria_id, type) VALUES (29, 'о котрій годині виїхали?', 17, 17, 'TIME');
INSERT INTO public.question (id, name, weight, criteria_id, type) VALUES (18, 'о котрій годині вийшли?', 14, 14, 'TIME');
INSERT INTO public.question (id, name, weight, criteria_id, type) VALUES (17, 'о котрій годині виїхали?', 14, 14, 'TIME');
INSERT INTO public.question (id, name, weight, criteria_id, type) VALUES (13, 'о котрій годині виїхали?', 13, 13, 'TIME');
INSERT INTO public.question (id, name, weight, criteria_id, type) VALUES (22, 'о котрій годині вийшли?', 15, 15, 'TIME');
INSERT INTO public.question (id, name, weight, criteria_id, type) VALUES (21, 'о котрій годині виїхали?', 15, 15, 'TIME');
INSERT INTO public.question (id, name, weight, criteria_id, type) VALUES (14, 'о котрій годині вийшли?', 13, 13, 'TIME');
INSERT INTO public.question (id, name, weight, criteria_id, type) VALUES (35, 'о котрій годині виїхали?', 19, 19, 'TIME');
INSERT INTO public.question (id, name, weight, criteria_id, type) VALUES (19, 'вкажіть початкову зупинку', 14, 14, 'ROUTE');
INSERT INTO public.question (id, name, weight, criteria_id, type) VALUES (16, 'вкажіть кінцеву зупинку', 13, 13, 'ROUTE');
INSERT INTO public.question (id, name, weight, criteria_id, type) VALUES (20, 'вкажіть кінцеву зупинку', 14, 14, 'ROUTE');
INSERT INTO public.question (id, name, weight, criteria_id, type) VALUES (15, 'вкажіть початкову зупинку', 13, 13, 'ROUTE');
INSERT INTO public.question (id, name, weight, criteria_id, type) VALUES (7, 'якість проїзду?', 7, 7, 'RATING');
INSERT INTO public.question (id, name, weight, criteria_id, type) VALUES (6, 'якість салону?', 6, 6, 'RATING');
INSERT INTO public.question (id, name, weight, criteria_id, type) VALUES (5, 'якість проїзду?', 5, 5, 'RATING');
INSERT INTO public.question (id, name, weight, criteria_id, type) VALUES (4, 'в скільки оцінюєте стан тролейбусу?', 4, 4, 'RATING');
INSERT INTO public.question (id, name, weight, criteria_id, type) VALUES (12, 'Чи задоволені маршруткою?', 12, 12, 'ACCEPTER');
INSERT INTO public.question (id, name, weight, criteria_id, type) VALUES (9, 'Чи задоволені тримваєм?', 9, 9, 'ACCEPTER');
INSERT INTO public.question (id, name, weight, criteria_id, type) VALUES (10, 'Чи задоволені тролейбусом?', 10, 10, 'ACCEPTER');
INSERT INTO public.question (id, name, weight, criteria_id, type) VALUES (31, 'оцініть завантаженість трамвая', 17, 17, 'CAPACITY');
INSERT INTO public.question (id, name, weight, criteria_id, type) VALUES (34, 'оцініть завантаженість тролейбуса', 18, 18, 'CAPACITY');
INSERT INTO public.question (id, name, weight, criteria_id, type) VALUES (11, 'Чи задоволені автобусом?', 11, 11, 'ACCEPTER');
INSERT INTO public.question (id, name, weight, criteria_id, type) VALUES (8, 'оцініть частоту появи маршруток на рейсі?', 8, 8, 'RATING');
INSERT INTO public.question (id, name, weight, criteria_id, type) VALUES (41, 'оцініть завантаженість маршрутки', 20, 18, 'CAPACITY');
INSERT INTO public.question (id, name, weight, criteria_id, type) VALUES (40, 'оцініть завантаженість автобуса', 19, 19, 'CAPACITY');
INSERT INTO public.question (id, name, weight, criteria_id, type) VALUES (3, 'якість проїзду?', 3, 3, 'RATING');
INSERT INTO public.question (id, name, weight, criteria_id, type) VALUES (2, 'якість обслуговуючого персоналу (водій , кондуктор)?', 2, 2, 'RATING');
INSERT INTO public.question (id, name, weight, criteria_id, type) VALUES (1, 'якість проїзду?', 6, 1, 'RATING');
INSERT INTO public.question (id, name, weight, criteria_id, type) VALUES (27, 'вкажіть початкову зупинку', 16, 19, 'ROUTE');
INSERT INTO public.question (id, name, weight, criteria_id, type) VALUES (23, 'вкажіть початкову зупинку', 15, 12, 'ROUTE');
INSERT INTO public.question (id, name, weight, criteria_id, type) VALUES (24, 'вкажіть кінцеву зупинку', 15, 14, 'ROUTE');
INSERT INTO public.question (id, name, weight, criteria_id, type) VALUES (28, 'вкажіть кінцеву зупинку', 16, 12, 'ROUTE');