INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (1, '[{"answer" : 2, "weight" :1}]', 1, 4, 1, null);
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (2, '[{"answer" : 10, "weight" :1}]', 1, 4, 1, null);
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (3, '[{"answer" : 5, "weight" :1}]', 2, 4, 1, null);
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (4, '[{"answer" : 10, "weight" :1}]', 1, 4, 1, null);
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (5, '[{"answer" : 7, "weight" :1}]', 2, 4, 1, null);
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (6, '[{"answer" : 5, "weight" :1}]', 3, 4, 1, null);
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (7, '[{"answer" : 2, "weight" :1}]', 4, 4, 1, null);
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (8, '[{"answer" : 10, "weight" :1}]', 5, 4, 1, null);
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (9, '[{"answer" : 9, "weight" :1}]', 6, 4, 1, null);
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (10, '[{"answer" : 8, "weight" :1}]', 7, 4, 1, null);
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (11, '[{"answer" : 10, "weight" :1}]', 1, 4, 1, null);
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (12, '[{"answer" : 7, "weight" :1}]', 2, 4, 1, null);
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (13, '[{"answer" : 5, "weight" :1}]', 3, 4, 1, null);
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (14, '[{"answer" : 2, "weight" :1}]', 4, 4, 1, null);
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (15, '[{"answer" : 10, "weight" :1}]', 5, 4, 1, null);
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (16, '[{"answer" : 9, "weight" :1}]', 6, 4, 1, null);
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (17, '[{"answer" : 8, "weight" :1}]', 7, 4, 1, null);
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (18, '"YES"', 8, 4, 2, null);
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (19, '"YES"', 10, 4, 2, null);
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (20, '"YES"', 11, 3, 1, null);
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (21, '"NO"', 9, 4, 1, null);
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (22, '{ "startTime" : {"hour":8, "minute":44}, "endTime":{"hour":9, "minute":44} , "capacity":30}', 16, 4, 2, null);
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (23, '{ "startTime" : {"hour":2, "minute":44}, "endTime":{"hour":3, "minute":44} , "capacity":30}', 18, 4, 1, null);
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (24, '{ "startTime" : {"hour":8, "minute":44}, "endTime":{"hour":9, "minute":44} , "capacity":30}', 15, 4, 3, null);
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (25, '{ "startTime" : {"hour":16, "minute":44}, "endTime":{"hour":17, "minute":44} , "capacity":30}', 17, 4, 3, null);
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (26, '{ "capacity":30, "from":{"street":"Автовокзал"} ,"to" :{"street":"вул. Скорини"}}', 13, 4, 3, null);
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (27, '{ "capacity":30, "from":{"street":"Автовокзал"} ,"to" :{"street":"Податкова"}}', 19, 4, 2, null);
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (28, '{ "capacity":10, "from":{"street":"Автовокзал"} ,"to" :{"street":"Податкова"}}', 14, 4, 1, null);
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (29, '{ "capacity":30, "from":{"street":"Автовокзал"} ,"to" :{"street":"вул. Скорини"}}', 12, 4, 3, null);
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (30, '"YES"', 9, 4, 1, null);
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (31, '[{"answer" : 5, "weight" :1}]', 2, 4, 1, null);
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (32, '[{"answer" : 5, "weight" :1}]', 3, 4, 1, null);
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (33, '"MAYBE"', 9, 4, 1, null);
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (34, '[{"answer" : 10, "weight" :1}]', 2, 4, 1, null);
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (35, '[{"answer" : 10, "weight" :1}]', 3, 4, 1, null);
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (36, '"NO"', 9, 4, 1, null);
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (37, '[{"answer" : 10, "weight" :1}]', 2, 4, 1, null);
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (38, '[{"answer" : 2, "weight" :1}]', 3, 4, 1, null);
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (39, '"NO"', 9, 4, 1, null);
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (40, '[{"answer" : 2, "weight" :1}]', 2, 4, 1, null);
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (41, '[{"answer" : 2, "weight" :1}]', 3, 4, 1, null);
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (45, '"NO"', 9, 3, 1, null);
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (48, '"NO"', 9, 3, 1, null);
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (44, '[{"answer" : 10, "weight" :1}]', 3, 3, 1, null);
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (47, '[{"answer" : 10, "weight" :1}]', 3, 3, 1, null);
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (46, '[{"answer" : 10, "weight" :1}]', 2, 3, 1, null);
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (43, '[{"answer" : 10, "weight" :1}]', 2, 3, 1, null);
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (42, '[{"answer" : 10, "weight" :1}]', 2, 4, 1, null);
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (51, '"NO"', 9, 3, 1, null);
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (50, '[{"answer" : 2, "weight" :1}]', 3, 3, 1, null);
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (49, '[{"answer" : 2, "weight" :1}]', 2, 3, 1, null);
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (54, '"NO"', 9, 3, 1, null);
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (53, '[{"answer" : 2, "weight" :1}]', 3, 3, 1, null);
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (52, '[{"answer" : 2, "weight" :1}]', 2, 3, 1, null);
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (55, '[{"answer":6,"weight":2}]', 2, 3, 1, '2018-07-06 09:46:33.855000');
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (56, '[{"answer":4,"weight":3}]', 3, 3, 1, '2018-07-06 09:46:33.900000');
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (57, '"NO"', 9, 3, 1, '2018-07-06 09:46:33.941000');
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (58, '{"startTime":{"hour":11,"minute":11},"endTime":{"hour":12,"minute":12},"capacity":"25"}', 16, 3, 1, '2018-07-06 09:46:34.018000');
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (59, '[{"answer":6,"weight":2}]', 2, 3, 1, '2018-07-06 09:48:29.041000');
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (60, '[{"answer":3,"weight":3}]', 3, 3, 1, '2018-07-06 09:48:29.108000');
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (61, '"NO"', 9, 3, 1, '2018-07-06 09:48:29.182000');
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (62, '{"startTime":{"hour":11,"minute":11},"endTime":{"hour":12,"minute":12},"capacity":"25"}', 16, 3, 1, '2018-07-06 09:48:29.271000');
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (63, '[{"answer":6,"weight":2}]', 2, 3, 1, '2018-07-06 09:55:27.623000');
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (64, '[{"answer":6,"weight":2}]', 3, 3, 1, '2018-07-06 09:55:27.697000');
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (65, '{"startTime":{"hour":11,"minute":11},"endTime":{"hour":12,"minute":12},"capacity":"25"}', 16, 3, 1, '2018-07-06 09:55:27.762000');
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (66, '[{"answer":4,"weight":6}]', 6, 10365, 1, '2018-07-06 10:11:26.649000');
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (67, '[{"answer":2,"weight":7}]', 7, 10365, 1, '2018-07-06 10:11:26.804000');
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (68, '"NO"', 11, 10365, 1, '2018-07-06 10:11:26.886000');
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (69, '{"startTime":{"hour":11,"minute":11},"endTime":{"hour":12,"minute":12},"capacity":"25"}', 18, 10365, 1, '2018-07-06 10:11:27.019000');
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (70, '{"startTime":{"hour":11,"minute":11},"endTime":{"hour":12,"minute":12},"capacity":"25"}', 18, 10365, 1, '2018-07-06 10:11:27.117000');
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (71, '"NO"', 10, 25, 1, '2018-07-06 10:13:14.360000');
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (72, '[{"answer":4,"weight":4}]', 4, 25, 1, '2018-07-06 10:13:14.506000');
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (73, '[{"answer":3,"weight":5}]', 5, 25, 1, '2018-07-06 10:13:14.634000');
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (74, '{"startTime":{"hour":11,"minute":11},"endTime":{"hour":12,"minute":12},"capacity":"25"}', 17, 25, 1, '2018-07-06 10:13:14.711000');
INSERT INTO public.feedback (id, answer, criteria_id, transit_id, user_id, date) VALUES (75, '{"startTime":{"hour":11,"minute":11},"endTime":{"hour":12,"minute":12},"capacity":"25"}', 17, 25, 1, '2018-07-06 10:13:14.796000');