INSERT INTO public.category (type, id, name, next_level_category_id, icon_url) VALUES ('EXTENDABLE', 1, 'Public Transport', null, 'static/bus.png');
INSERT INTO public.category (type, id, name, next_level_category_id, icon_url) VALUES ('EXTENDABLE', 8, 'Taxi', null, 'static/taxi.png');
INSERT INTO public.category (type, id, name, next_level_category_id, icon_url) VALUES ('EXTENDABLE', 2, 'Lviv', 1, 'static/lviv.png');
INSERT INTO public.category (type, id, name, next_level_category_id, icon_url) VALUES ('EXTENDABLE', 3, 'Kyiv', 1, 'static/kyiv.png');
INSERT INTO public.category (type, id, name, next_level_category_id, icon_url) VALUES ('NON_EXTENDABLE', 4, 'Tram', 2, 'static/tram.png');
INSERT INTO public.category (type, id, name, next_level_category_id, icon_url) VALUES ('NON_EXTENDABLE', 5, 'Trolleybus', 2, 'static/trolleybus.png');
INSERT INTO public.category (type, id, name, next_level_category_id, icon_url) VALUES ('NON_EXTENDABLE', 6, 'Bus', 2, 'static/bigbus.png');
INSERT INTO public.category (type, id, name, next_level_category_id, icon_url) VALUES ('NON_EXTENDABLE', 7, 'Marshrutka', 2, 'static/van.png');

INSERT INTO public.geotag (id, latitude, longtitude, name) VALUES (1, 49.83826, 24.02324, '#Lviv');
INSERT INTO public.geotag (id, latitude, longtitude, name) VALUES (2, 50.4501, 30.5234, '#Kyiv');

update public.category set geotag_id=1 where id=2;
update public.category set geotag_id=2 where id=3;


-- -- INSERT INTO public.question (id, name, weight, criteria_id) VALUES (2, 'якість обслуговуючого персоналу (водій , кондуктор)?', 2, 2);
-- -- INSERT INTO public.question (id, name, weight, criteria_id) VALUES (3, 'якість проїзду?', 3, 3);
-- -- INSERT INTO public.question (id, name, weight, criteria_id) VALUES (4, 'в скільки оцінюєте стан тролейбусу?', 4, 4);
-- -- INSERT INTO public.question (id, name, weight, criteria_id) VALUES (5, 'якість проїзду?', 5, 5);
-- -- INSERT INTO public.question (id, name, weight, criteria_id) VALUES (6, 'якість салону?', 6, 6);
-- -- INSERT INTO public.question (id, name, weight, criteria_id) VALUES (7, 'якість проїзду?', 7, 7);
-- -- INSERT INTO public.question (id, name, weight, criteria_id) VALUES (8, 'оцініть частоту появи маршруток на рейсі?', 8, 8);
-- -- INSERT INTO public.question (id, name, weight, criteria_id) VALUES (9, 'Чи задоволені тримваєм?', 9, 9);
-- -- INSERT INTO public.question (id, name, weight, criteria_id) VALUES (10, 'Чи задоволені тролейбусом?', 10, 10);
-- -- INSERT INTO public.question (id, name, weight, criteria_id) VALUES (11, 'Чи задоволені автобусом?', 11, 11);
-- -- INSERT INTO public.question (id, name, weight, criteria_id) VALUES (12, 'Чи задоволені маршруткою?', 12, 12);
-- -- INSERT INTO public.question (id, name, weight, criteria_id) VALUES (13, 'о котрій годині виїхали?', 13, 13);
-- -- INSERT INTO public.question (id, name, weight, criteria_id) VALUES (14, 'о котрій годині вийшли?', 13, 13);
-- -- INSERT INTO public.question (id, name, weight, criteria_id) VALUES (15, 'вкажіть початкову зупинку', 13, 13);
-- -- INSERT INTO public.question (id, name, weight, criteria_id) VALUES (16, 'вкажіть кінцеву зупинку', 13, 13);
-- -- INSERT INTO public.question (id, name, weight, criteria_id) VALUES (17, 'о котрій годині виїхали?', 14, 14);
-- -- INSERT INTO public.question (id, name, weight, criteria_id) VALUES (18, 'о котрій годині вийшли?', 14, 14);
-- -- INSERT INTO public.question (id, name, weight, criteria_id) VALUES (19, 'вкажіть початкову зупинку', 14, 14);
-- -- INSERT INTO public.question (id, name, weight, criteria_id) VALUES (20, 'вкажіть кінцеву зупинку', 14, 14);
-- -- INSERT INTO public.question (id, name, weight, criteria_id) VALUES (21, 'о котрій годині виїхали?', 15, 15);
-- -- INSERT INTO public.question (id, name, weight, criteria_id) VALUES (22, 'о котрій годині вийшли?', 15, 15);
-- -- INSERT INTO public.question (id, name, weight, criteria_id) VALUES (23, 'вкажіть початкову зупинку', 15, 15);
-- -- INSERT INTO public.question (id, name, weight, criteria_id) VALUES (24, 'вкажіть кінцеву зупинку', 15, 15);
-- -- INSERT INTO public.question (id, name, weight, criteria_id) VALUES (25, 'о котрій годині виїхали?', 16, 16);
-- -- INSERT INTO public.question (id, name, weight, criteria_id) VALUES (26, 'о котрій годині вийшли?', 16, 16);
-- -- INSERT INTO public.question (id, name, weight, criteria_id) VALUES (27, 'вкажіть початкову зупинку', 16, 16);
-- -- INSERT INTO public.question (id, name, weight, criteria_id) VALUES (28, 'вкажіть кінцеву зупинку', 16, 16);
-- -- INSERT INTO public.question (id, name, weight, criteria_id) VALUES (29, 'о котрій годині виїхали?', 17, 17);
-- -- INSERT INTO public.question (id, name, weight, criteria_id) VALUES (30, 'о котрій годині вийшли?', 17, 17);
-- -- INSERT INTO public.question (id, name, weight, criteria_id) VALUES (31, 'оцініть завантаженість трамвая', 17, 17);
-- -- INSERT INTO public.question (id, name, weight, criteria_id) VALUES (32, 'о котрій годині виїхали?', 18, 18);
-- -- INSERT INTO public.question (id, name, weight, criteria_id) VALUES (33, 'о котрій годині вийшли?', 18, 18);
-- -- INSERT INTO public.question (id, name, weight, criteria_id) VALUES (34, 'оцініть завантаженість тролейбуса', 18, 18);
-- -- INSERT INTO public.question (id, name, weight, criteria_id) VALUES (35, 'о котрій годині виїхали?', 19, 19);
-- -- INSERT INTO public.question (id, name, weight, criteria_id) VALUES (36, 'о котрій годині виїхали?', 19, 19);
-- -- INSERT INTO public.question (id, name, weight, criteria_id) VALUES (37, 'о котрій годині виїхали?', 20, 18);
-- -- INSERT INTO public.question (id, name, weight, criteria_id) VALUES (38, 'о котрій годині вийшли?', 19, 19);
-- -- INSERT INTO public.question (id, name, weight, criteria_id) VALUES (39, 'о котрій годині вийшли?', 20, 18);
-- -- INSERT INTO public.question (id, name, weight, criteria_id) VALUES (40, 'оцініть завантаженість автобуса', 19, 19);
-- -- INSERT INTO public.question (id, name, weight, criteria_id) VALUES (41, 'оцініть завантаженість маршрутки', 20, 18);
-- -- INSERT INTO public.question (id, name, weight, criteria_id) VALUES (1, 'якість проїзду?', 6, 1);
--
-- -- INSERT INTO public.feedback ( answer, criteria_id, transit_id, user_id) VALUES ( '[{"answer" : 2, "weight" :1}]', 1, 4, 1);
-- -- INSERT INTO public.feedback ( answer, criteria_id, transit_id, user_id) VALUES ( '[{"answer" : 10, "weight" :1}]', 1, 4, 1);
-- -- INSERT INTO public.feedback ( answer, criteria_id, transit_id, user_id) VALUES ( '[{"answer" : 5, "weight" :1}]', 2, 4, 1);
-- -- INSERT INTO public.feedback ( answer, criteria_id, transit_id, user_id) VALUES ( '[{"answer" : 10, "weight" :1}]', 1, 4, 1);
-- -- INSERT INTO public.feedback ( answer, criteria_id, transit_id, user_id) VALUES ( '[{"answer" : 7, "weight" :1}]', 2, 4, 1);
-- -- INSERT INTO public.feedback ( answer, criteria_id, transit_id, user_id) VALUES ( '[{"answer" : 5, "weight" :1}]', 3, 4, 1);
-- -- INSERT INTO public.feedback ( answer, criteria_id, transit_id, user_id) VALUES ( '[{"answer" : 2, "weight" :1}]', 4, 4, 1);
-- -- INSERT INTO public.feedback ( answer, criteria_id, transit_id, user_id) VALUES ( '[{"answer" : 10, "weight" :1}]', 5, 4, 1);
-- -- INSERT INTO public.feedback ( answer, criteria_id, transit_id, user_id) VALUES ( '[{"answer" : 9, "weight" :1}]', 6, 4, 1);
-- -- INSERT INTO public.feedback ( answer, criteria_id, transit_id, user_id) VALUES ( '[{"answer" : 8, "weight" :1}]', 7, 4, 1);
-- -- INSERT INTO public.feedback ( answer, criteria_id, transit_id, user_id) VALUES ( '[{"answer" : 10, "weight" :1}]', 1, 4, 1);
-- -- INSERT INTO public.feedback ( answer, criteria_id, transit_id, user_id) VALUES ( '[{"answer" : 7, "weight" :1}]', 2, 4, 1);
-- -- INSERT INTO public.feedback ( answer, criteria_id, transit_id, user_id) VALUES ( '[{"answer" : 5, "weight" :1}]', 3, 4, 1);
-- -- INSERT INTO public.feedback ( answer, criteria_id, transit_id, user_id) VALUES ( '[{"answer" : 2, "weight" :1}]', 4, 4, 1);
-- -- INSERT INTO public.feedback ( answer, criteria_id, transit_id, user_id) VALUES ( '[{"answer" : 10, "weight" :1}]', 5, 4, 1);
-- -- INSERT INTO public.feedback ( answer, criteria_id, transit_id, user_id) VALUES ( '[{"answer" : 9, "weight" :1}]', 6, 4, 1);
-- -- INSERT INTO public.feedback ( answer, criteria_id, transit_id, user_id) VALUES ( '[{"answer" : 8, "weight" :1}]', 7, 4, 1);
-- -- INSERT INTO public.feedback ( answer, criteria_id, transit_id, user_id) VALUES ( '"YES"', 8, 4, 2);
-- -- INSERT INTO public.feedback ( answer, criteria_id, transit_id, user_id) VALUES ( '"YES"', 10, 4, 2);
-- -- INSERT INTO public.feedback ( answer, criteria_id, transit_id, user_id) VALUES ( '"YES"', 11, 3, 1);
-- -- INSERT INTO public.feedback ( answer, criteria_id, transit_id, user_id) VALUES ( '"NO"', 9, 4, 1);
-- -- INSERT INTO public.feedback ( answer, criteria_id, transit_id, user_id) VALUES ( '{ "startTime" : {"hour":8, "minute":44}, "endTime":{"hour":9, "minute":44} , "capacity":30}', 16, 4, 2);
-- -- INSERT INTO public.feedback ( answer, criteria_id, transit_id, user_id) VALUES ( '{ "startTime" : {"hour":2, "minute":44}, "endTime":{"hour":3, "minute":44} , "capacity":30}', 18, 4, 1);
-- -- INSERT INTO public.feedback ( answer, criteria_id, transit_id, user_id) VALUES ( '{ "startTime" : {"hour":8, "minute":44}, "endTime":{"hour":9, "minute":44} , "capacity":30}', 15, 4, 3);
-- -- INSERT INTO public.feedback ( answer, criteria_id, transit_id, user_id) VALUES ( '{ "startTime" : {"hour":16, "minute":44}, "endTime":{"hour":17, "minute":44} , "capacity":30}', 17, 4, 3);
-- -- INSERT INTO public.feedback ( answer, criteria_id, transit_id, user_id) VALUES ( '{ "capacity":30, "from":{"street":"Автовокзал"} ,"to" :{"street":"вул. Скорини"}}', 13, 4, 3);
-- -- INSERT INTO public.feedback ( answer, criteria_id, transit_id, user_id) VALUES ( '{ "capacity":30, "from":{"street":"Автовокзал"} ,"to" :{"street":"Податкова"}}', 19, 4, 2);
-- -- INSERT INTO public.feedback ( answer, criteria_id, transit_id, user_id) VALUES ( '{ "capacity":10, "from":{"street":"Автовокзал"} ,"to" :{"street":"Податкова"}}', 14, 4, 1);
-- -- INSERT INTO public.feedback ( answer, criteria_id, transit_id, user_id) VALUES ( '{ "capacity":30, "from":{"street":"Автовокзал"} ,"to" :{"street":"вул. Скорини"}}', 12, 4, 3);
-- -- INSERT INTO public.feedback ( answer, criteria_id, transit_id, user_id) VALUES ( '"YES"', 9, 4, 1);
-- -- INSERT INTO public.feedback ( answer, criteria_id, transit_id, user_id) VALUES ( '[{"answer" : 5, "weight" :1}]', 2, 4, 1);
-- -- INSERT INTO public.feedback ( answer, criteria_id, transit_id, user_id) VALUES ( '[{"answer" : 5, "weight" :1}]', 3, 4, 1);
-- -- INSERT INTO public.feedback ( answer, criteria_id, transit_id, user_id) VALUES ( '"MAYBE"', 9, 4, 1);
-- -- INSERT INTO public.feedback ( answer, criteria_id, transit_id, user_id) VALUES ( '[{"answer" : 10, "weight" :1}]', 2, 4, 1);
-- -- INSERT INTO public.feedback ( answer, criteria_id, transit_id, user_id) VALUES ( '[{"answer" : 10, "weight" :1}]', 3, 4, 1);
-- -- INSERT INTO public.feedback ( answer, criteria_id, transit_id, user_id) VALUES ( '"NO"', 9, 4, 1);
-- -- INSERT INTO public.feedback ( answer, criteria_id, transit_id, user_id) VALUES ( '[{"answer" : 10, "weight" :1}]', 2, 4, 1);
-- -- INSERT INTO public.feedback ( answer, criteria_id, transit_id, user_id) VALUES ( '[{"answer" : 2, "weight" :1}]', 3, 4, 1);
-- -- INSERT INTO public.feedback ( answer, criteria_id, transit_id, user_id) VALUES ( '"NO"', 9, 4, 1);
-- -- INSERT INTO public.feedback ( answer, criteria_id, transit_id, user_id) VALUES ( '[{"answer" : 2, "weight" :1}]', 2, 4, 1);
-- -- INSERT INTO public.feedback ( answer, criteria_id, transit_id, user_id) VALUES ( '[{"answer" : 2, "weight" :1}]', 3, 4, 1);
